language: php
php:
  - '7.2'
  - nightly

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE sitetpl_test;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.dusk .env
  - php artisan serve &

install:
  - composer install

script:
  - php artisan cc:all
  - php artisan dusk