language: php
php:
  - '7.2'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE sitetpl_dusk;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.dusk .env

install:
  - composer install
  - php artisan migrate --env=dusk

script:
  - php artisan cc:all
  - php artisan serve --port=8088 &
  - php artisan dusk --env=dusk